# Generated by Django 4.2.7 on 2023-11-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=500)),
                ('sentiment', models.CharField(max_length=255)),
            ],
        ),
    ]
