# Generated by Django 4.2.7 on 2023-11-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_analysis',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
